from rdkit import Chem
from rdkit.Chem import AllChem
import numpy as np
from pharmacophoremt import pyunitwizard as puw

def to_sdf(pharmacophore, file_name):
    """Export a pharmacophore to an annotated SDF file using RDKit.
    
    Each interaction site is represented as a virtual atom with 
    associated metadata in SD tags.
    """
    mol = Chem.Mol()
    editable_mol = Chem.EditableMol(mol)
    
    conf = Chem.Conformer(pharmacophore.n_interaction_sites)
    
    for i, site in enumerate(pharmacophore.interaction_sites):
        # Add a dummy atom (e.g., Helium 'He')
        idx = editable_mol.AddAtom(Chem.Atom(2)) 
        
        center = puw.get_value(site.center, to_unit='angstroms')
        conf.SetAtomPosition(idx, (float(center[0]), float(center[1]), float(center[2])))

    mol = editable_mol.GetMol()
    mol.AddConformer(conf)
    
    # Annotate with tags
    for i, site in enumerate(pharmacophore.interaction_sites):
        mol.SetProp(f"SITE_{i}_FEATURES", "|".join(site.features))
        mol.SetProp(f"SITE_{i}_SHAPE", site.shape_name)
        mol.SetProp(f"SITE_{i}_RADIUS", str(puw.get_value(site.radius, to_unit='angstroms')))

    writer = Chem.SDWriter(file_name)
    writer.write(mol)
    writer.close()

def load_sdf(file_name):
    """Load a pharmacophore from an annotated SDF file.
    
    Note: Currently only supports SDFs generated by pharmacophoremt.
    """
    from pharmacophoremt.pharmacophore import Pharmacophore
    from pharmacophoremt import interaction_site as interaction_sites
    from pharmacophoremt.interaction_site.shape import Sphere
    
    suppl = Chem.SDMolSupplier(file_name)
    mol = next(suppl)
    if mol is None:
        return None
        
    ph = Pharmacophore()
    conf = mol.GetConformer()
    
    n_atoms = mol.GetNumAtoms()
    for i in range(n_atoms):
        pos = conf.GetAtomPosition(i)
        center = puw.quantity([pos.x, pos.y, pos.z], 'angstroms')
        
        # Try to recover from tags
        features = mol.GetProp(f"SITE_{i}_FEATURES").split("|")
        radius_val = float(mol.GetProp(f"SITE_{i}_RADIUS"))
        radius = puw.quantity(radius_val, 'angstroms')
        
        # Create a generic interaction site
        # In Gen 1, we assume all SDF sites are spheres unless specified
        site = interaction_sites.InteractionSite(Sphere(center, radius), features)
        ph.add_interaction_site(site)
        
    return ph
